sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: s6MDhFv76TKkoeZPpThiM6vP3FMeLhRRIOQLN3JCDbCTDTKARsj79r3FOgpOaI0TBD/wW2Pd7VCVktLNkDV/MNM3Svs8A+to/7tbQRdgVu2HEqkDwvtUqPJ5GTi3zatVvVCSCJzBmKnqTOUszC0caO4DGqE0vF4CdzzWPALd4sf63U1Rfs5+HBOZcptMCt80grpWn4yQeX1Uz4rMNktvee6JPM+scXLdApsoM6VKo2vuynvJKspPcDzYYbcRqV9384BQ0WYHs3rjgNfbA8+h5qR4hxb4qayfCCGILgEDvJnGrLbozNpQEkmWCZS5Xy1UoLoKcakpVodHVD4Bsb00O2Bx5RHpV4OyiyLJ/KToupkwXoZFd2c0QEqvn2gTrMvaHArG7YduL2O90/79J+VdJZJOyo8OY2+Y+/jIti6TBeK1nlnm74HK7En4DTSi831qdSq9ucNxrP9TzyBJgrPOqt8yl7XgT5Uv7khK8kd5ZKSKL8Wl1ft7aaAlxiEb6s9FlwUdiPeGREIw6QgHpmQz7/2EBK2m/8nHkzCw00sUycC/FpFDSHRxQ3KA+bvX/9VWa8AIe3pEA7INmyfY8a/K3eNfScaH345zFE7SUQ+MENKhlp4Ibdu1q0mvp2xTCcIw8Zjg8Z9jVkJulbc0NheuXz7L7d+7/HhU6C1P8eiVvjg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Raspberry-Jam_5335
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy